server:
  port: 9099

spring:
  security:
    oauth2:
      client:
        provider:
          licencia-realm:
            issuer-uri: http://localhost:8080/realms/licencia-realm
        registration:
          licencia-realm:
            provider: licencia-realm
            client-name: licencia-keycloack-client
            client-id: licencia-keycloack-client
            client-secret: 6vcxM3mqbvjvzFuOiJgQwS3nbeO83ZVP
            scope: openid
            authorization-grant-type: authorization_code
