server:
  port: ${CUSTOM.SERVER.PORT:9011}

spring:
  data:
    mongodb:
      uri: ${MONGODB.URL.CONNECTION:mongodb://hjara:hjara@localhost:27017/licenciasdb?authSource=admin}

#Actuator configuration
info:
  app:
    name: Licencia Service 
    description: Módulo de la arquitectura de Microservicios que disponibiliza la información de las licencias
    version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: /actuator

#OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
