server:
  port: ${CUSTOM.SERVER.PORT:9010}

spring:
  data:
    mongodb:
      uri: mongodb://hjara:hjara@localhost:27018/licenciasdb?authSource=admin


management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: /actuator
