server:
  port: ${CUSTOM.SERVER.PORT:9010}
  
### Mongo database configuration
spring:
  data:
    mongodb:
      uri: ${MONGODB.URL.CONNECTION:mongodb://hjara:hjara@localhost:27017/licenciasdb?authSource=admin}

management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: /actuator
